Feat: Создать фичу - комментарии
IagoDevJava/java-explore-with-me pull request #10
Opened 2023-03-06 04:52 UTC by IagoDevJava

2023-03-06 21:37 UTC, sergeymamonov requested changes

2023-03-06 21:37 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/chart_private/controller/PrivateCommentController.java
> +    //    @GetMapping()
Не оставляйте в проекте закомментированный код.

2023-03-06 21:37 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/chart_private/service/PrivateCommentService.java
> +//    List<CommentDto> getAllByAuthorId(Long userId);
Закомментированный код.

2023-03-06 21:37 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/chart_private/service/PrivateCommentServiceImpl.java
> +//    @Override
Удалить.

2023-03-07 04:44 UTC, IagoDevJava commented on main-service/src/main/java/ru/practicum/chart_private/controller/PrivateCommentController.java
> +    //    @GetMapping()
Хорошо

2023-03-07 04:44 UTC, IagoDevJava commented on main-service/src/main/java/ru/practicum/chart_private/service/PrivateCommentService.java
> +//    List<CommentDto> getAllByAuthorId(Long userId);
Сделано

2023-03-07 04:44 UTC, IagoDevJava commented on main-service/src/main/java/ru/practicum/chart_private/service/PrivateCommentServiceImpl.java
> +//    @Override
Сделано

2023-03-07 04:45 UTC, IagoDevJava commented
Сергей, прошу прощения за закомментированный код. Весь диплом пишу с температурой - отсюда такая невнимательность.

2023-03-08 03:58 UTC, sergeymamonov approved these changes

2023-03-08 04:41 UTC, merged