add Сервис статистики
IagoDevJava/java-explore-with-me pull request #8
Opened 2023-02-24 10:08 UTC by IagoDevJava

2023-02-24 10:13 UTC, IagoDevJava commented
![Снимок экрана 2023-02-24 161058](https://user-images.githubusercontent.com/66621400/221152677-8a09efd5-6a10-4c1f-b196-54e5754346c3.jpg)
Что-то знакомое - не могу понять решал эту проблему как-то или пропускали ее

2023-02-25 10:45 UTC, sergeymamonov requested changes
Сборка не проходит. Сдавать на проверку нужно с проходящей сборкой. В ошибке сказано, что не может найти stat-**server**. При этом есть модуль stat-**service**. На всякий случай, обращаю внимание, что у нас используется 11 версия Java.

2023-02-25 10:45 UTC, sergeymamonov commented on pom.xml
> +<!--		<module>stat/stat-service</module>-->
В проекте не должно быть никакого закомментированного кода.

2023-02-25 10:45 UTC, sergeymamonov commented on stat/stat-dto/src/main/java/Main.java
> +    public static void main(String[] args) {
В этом модуле не должно быть Main класса. Мы же не планируем запускать в этом модуле ничего.

2023-02-25 10:45 UTC, sergeymamonov commented on stat/stat-dto/pom.xml
> +<!--    <packaging>pom</packaging>-->
Закомментированный код.

2023-02-25 10:45 UTC, sergeymamonov commented on stat/stat-service/Dockerfile
> +    && RPM_LIST=("java-17-amazon-corretto-headless-$version.amzn2022.${package_version}.$(uname -m).rpm" "java-17-amazon-corretto-$version.amzn2022.${package_version}.$(uname -m).rpm" "java-17-amazon
У нас 11 Java.

2023-02-25 10:45 UTC, sergeymamonov commented on stat/stat-service/src/main/resources/schema.sql
> +    APP  varchar,
Лучше ограничивать размер varchar.

2023-02-25 10:45 UTC, sergeymamonov commented on stat/stat-service/src/main/resources/schema.sql
> +    URI  varchar,
Лучше продублировать на уровне БД ограничения, которые накладываются на эти поля.

2023-02-25 10:45 UTC, sergeymamonov commented on stat/stat-client/src/main/java/ru/practicum/stat/StatClient.java
> +    private static final String API_PREFIX = ""; // Не понял из ТЗ надо ли тут ставить префикс
Здесь ли выделить в константу слеш и использовать его дальше, или использовать слеш в строке эндпоинта, как сделано в строке 34 - это на ваше усмотрение. Главное, чтобы клиент шел на верные эндпоинты. Можно запускать тесты Постмана и смотреть в дебагере, куда идут запросы.

2023-02-25 14:03 UTC, IagoDevJava commented on pom.xml
> +<!--		<module>stat/stat-service</module>-->
ok

2023-02-25 14:03 UTC, IagoDevJava commented on stat/stat-dto/pom.xml
> +<!--    <packaging>pom</packaging>-->
ok

2023-02-25 14:06 UTC, IagoDevJava commented on stat/stat-service/src/main/resources/schema.sql
> +    APP  varchar,
ok

2023-02-25 14:06 UTC, IagoDevJava commented on stat/stat-service/src/main/resources/schema.sql
> +    URI  varchar,
ok

2023-02-25 14:07 UTC, IagoDevJava commented on stat/stat-client/src/main/java/ru/practicum/stat/StatClient.java
> +    private static final String API_PREFIX = ""; // Не понял из ТЗ надо ли тут ставить префикс
ok

2023-02-27 15:22 UTC, IagoDevJava commented on stat/stat-dto/src/main/java/Main.java
> +    public static void main(String[] args) {
ок

2023-02-27 15:23 UTC, IagoDevJava commented on stat/stat-service/Dockerfile
> +    && RPM_LIST=("java-17-amazon-corretto-headless-$version.amzn2022.${package_version}.$(uname -m).rpm" "java-17-amazon-corretto-$version.amzn2022.${package_version}.$(uname -m).rpm" "java-17-amazon
Разве это имеет значение? Нигде не было указано работать именно на 11 версии

2023-02-28 09:42 UTC, IagoDevJava commented
![Снимок экрана 2023-02-28 153631](https://user-images.githubusercontent.com/66621400/221814459-96cc371c-8d99-4bc8-961b-7c6481f9a487.jpg)
![Снимок экрана 2023-02-28 153713](https://user-images.githubusercontent.com/66621400/221814469-f68c539a-b099-4016-864b-4027b2fac9f3.jpg)
![Снимок экрана 2023-02-28 154131](https://user-images.githubusercontent.com/66621400/221814470-d5c8a0f7-a996-4885-a71e-7b73bf8fe258.jpg)

2023-02-28 09:43 UTC, IagoDevJava commented
Code 124 уже не в первый раз выскакивает.
Наставник не смог помочь как от него избавиться, ревьюер принимал с ним как правило.

2023-03-01 08:37 UTC, sergeymamonov commented
К сожалению, проект с красной сборкой принять не имею права. Обратите внимание на версию Java. У нас 11 и это важно. Попробуйте запустить docker-compose локально и посмотреть, как будут запускаться приложения.

2023-03-01 08:40 UTC, sergeymamonov requested changes

2023-03-01 08:40 UTC, sergeymamonov commented on main-service/pom.xml
> +<!--        <dependency>-->
Не оставляйте закомментированного кода.

2023-03-01 08:40 UTC, sergeymamonov commented on pom.xml
> -		<java.version>11</java.version>
У нас используется 11 версия Java, не 17. Это важно, некоторые проверки могут не проходить из-за этого.

2023-03-01 08:40 UTC, sergeymamonov commented on stat/stat-service/Dockerfile
> +    && RPM_LIST=("java-17-amazon-corretto-headless-$version.amzn2022.${package_version}.$(uname -m).rpm" "java-17-amazon-corretto-$version.amzn2022.${package_version}.$(uname -m).rpm" "java-17-amazon
Да, важно. У нас 11 версия. Из-за этого могут не проходить часть проверок.

2023-03-01 10:00 UTC, IagoDevJava commented
Сергей, если Вы, не обратили внимания, то я изменил сборку на 11 Java
От этого ничего не меняется

2023-03-01 10:02 UTC, IagoDevJava commented
Так же я приложил скриншот, что локально всё запущено и тесты пройдены. 
Если у вас есть варианты решения проблемы - готов выслушать. Как я уже говорил - наставник не смог помочь. И данная ошибка выскакивает с завидной периодичностью у многих. Как правило именно с этой ошибкой принимают проект.

2023-03-01 10:14 UTC, IagoDevJava commented on main-service/pom.xml
> +<!--        <dependency>-->
ок

2023-03-01 10:14 UTC, IagoDevJava commented on pom.xml
> -		<java.version>11</java.version>
Я уже изменил все на 11ю

2023-03-02 05:23 UTC, sergeymamonov approved these changes

2023-03-02 07:48 UTC, merged