add Main svc
IagoDevJava/java-explore-with-me pull request #9
Opened 2023-03-03 13:24 UTC by IagoDevJava

2023-03-04 13:37 UTC, sergeymamonov requested changes
В проекте имеются пакеты с неверными наименованиями

2023-03-04 13:37 UTC, sergeymamonov commented on stat/stats-server/src/main/resources/schema.sql
>      URI  varchar,
Размер varchar лучше ограничивать.

2023-03-04 13:37 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/chartAdmin/controller/CategoryController.java
> +package ru.practicum.chartAdmin.controller;
chartAdmin - неверное наименование пакета. Пакеты именуются в snake_case

2023-03-04 13:37 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/chartAdmin/controller/CategoryController.java
> +    public CategoryController(AdminCategoryService service) {
Можно не писать конструктор руками @AllArgsConstructor. Во всех остальных классах аналогично.

2023-03-04 13:37 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/chartAdmin/controller/EventController.java
> +                                                                   @RequestParam(defaultValue = "0") Integer from,
Лучше провалидировать входное значение, потому что пользователь может передать отрицательное значение.

2023-03-04 13:37 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/chartPrivate/service/PrivateEventServiceImpl.java
> +        if (event.getState().equals(State.PUBLISHED)) {
event.getState(), то будет null.equals(), то есть NPE. Поэтому лучше делать так State.PUBLISHED.equals(event.getState())

2023-03-04 13:37 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/chartPublic/service/PublicEventServiceImpl.java
> +                .get();
Прежде чем вызвать метод get у Optional, нужно проверить содержимое Optional на null, иначе можно получить NPE. Посмотрите, какие для этой проверки есть методы у Optional.

2023-03-04 14:18 UTC, IagoDevJava commented
Сергей, Вы вроде говорили, что "красный" Проект не имеете права принять. 
Ну так - этот "зелёный". В чем проблема?

2023-03-04 14:34 UTC, IagoDevJava commented on stat/stats-server/src/main/resources/schema.sql
>      URI  varchar,
ок

2023-03-04 14:36 UTC, IagoDevJava commented on main-service/src/main/java/ru/practicum/chartAdmin/controller/CategoryController.java
> +package ru.practicum.chartAdmin.controller;
ок

2023-03-04 14:49 UTC, IagoDevJava commented on main-service/src/main/java/ru/practicum/chartAdmin/controller/CategoryController.java
> +    public CategoryController(AdminCategoryService service) {
ok

2023-03-04 14:53 UTC, IagoDevJava commented on main-service/src/main/java/ru/practicum/chartAdmin/controller/EventController.java
> +                                                                   @RequestParam(defaultValue = "0") Integer from,
ok

2023-03-04 14:55 UTC, IagoDevJava commented on main-service/src/main/java/ru/practicum/chartPrivate/service/PrivateEventServiceImpl.java
> +        if (event.getState().equals(State.PUBLISHED)) {
ok

2023-03-04 15:01 UTC, IagoDevJava commented on main-service/src/main/java/ru/practicum/chartPublic/service/PublicEventServiceImpl.java
> +                .get();
ok

2023-03-05 12:34 UTC, sergeymamonov approved these changes
Проверьте проект на вызов equals. Чтобы избежать NPE вызывайте equals у перечисления. И статус не нужно хранить в строке.

2023-03-05 12:34 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/chart_private/service/PrivateEventServiceImpl.java
> +        String status = eventRequestStatusUpdateRequest.getStatus();
Не очень хорошее решение, что статус строка, а не перечисление. То есть корни в StatusUpdateRequest. Лучше сделать в этом классе статус не строкой, а перечислением. И в строке 125 вызывать equals у перечисления, чтобы избежать NPE.

2023-03-05 12:34 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/chart_public/service/PublicEventServiceImpl.java
> +        if (!event.getState().equals(State.PUBLISHED)) {
equals нужно вызывать у перечисления, чтобы избежать NPE, если event.getState() будет равен null. Это для всех случаев использования equals.

2023-03-05 12:57 UTC, IagoDevJava commented on main-service/src/main/java/ru/practicum/chart_public/service/PublicEventServiceImpl.java
> +        if (!event.getState().equals(State.PUBLISHED)) {
ok

2023-03-05 13:00 UTC, IagoDevJava commented on main-service/src/main/java/ru/practicum/chart_private/service/PrivateEventServiceImpl.java
> +        String status = eventRequestStatusUpdateRequest.getStatus();
ok

2023-03-05 13:28 UTC, merged